# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: macos-large

steps:
  - label: ":xcode: Build and Test"
    key: build_and_test
    command: .buildkite/commands/build.sh
    artifact_paths:
      - "build/buildkite/logs/**/*.log"
      - "build/buildkite/results/**/*"

  - group: "Static Checks"
    steps:
      - label: ":mag: Static Checks"
        key: static_checks
        command: .buildkite/commands/static-checks.sh
        artifact_paths:
          - "build/buildkite/logs/**/*.log"

      - label: ":danger: Danger"
        key: danger
        command: .buildkite/commands/danger.sh
        if: "build.pull_request.id != null"
        retry:
          manual:
            permit_on_passed: true

      - label: ":sleuth_or_spy: Lint Localized Strings Format"
        key: localization_lint
        command: .buildkite/commands/localization-lint.sh

  - group: "Distribution"
    if: build.env("ENABLE_DISTRIBUTION_JOBS") == "true"
    steps:
      - label: "Build tvOS (App Store Connect)"
        key: build_tvos_app_store
        command: .buildkite/commands/build-tvos-app-store.sh
        artifact_paths:
          - artifacts/*.ipa
          - artifacts/*.app.dSYM.zip

      - input: "Upload tvOS to TestFlight"
        prompt: "Upload the tvOS build to TestFlight?"
        key: upload_tvos_testflight_input
        if: "build.branch != 'trunk'"

      - label: "Upload tvOS to TestFlight"
        key: upload_tvos_testflight
        depends_on:
          - build_tvos_app_store
          - upload_tvos_testflight_input
        command: .buildkite/commands/upload-tvos-app-store.sh
