# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# This pipeline is meant to be run via the Buildkite API, and is only used for release builds.

agents:
  queue: macos-large

steps:
  - label: "Release Build (App Store Connect)"
    key: testflight_build
    command: .buildkite/commands/release-build.sh "${RELEASE_VERSION}"
    priority: 1
    artifact_paths:
      - artifacts/*.ipa
      - artifacts/*.zip
    notify:
      - slack: "#build-and-ship"

  - label: "Release Upload (TestFlight, GitHub)"
    depends_on: testflight_build
    command: .buildkite/commands/release-upload.sh "${RELEASE_VERSION}" "${BETA_RELEASE}"
    priority: 1
    notify:
      - slack: "#build-and-ship"
