// ************ WARNING AUTO GENERATED, DO NOT EDIT ************
nonisolated enum ThemeStyle: CaseIterable {
    case primaryUi01,
         primaryUi01Active,
         primaryUi02,
         primaryUi02Selected,
         primaryUi02Active,
         primaryUi03,
         primaryUi04,
         primaryUi05,
         primaryUi05Selected,
         primaryUi06,
         primaryIcon01,
         primaryIcon01Active,
         primaryIcon02,
         primaryIcon02Selected,
         primaryIcon02Active,
         primaryIcon03,
         primaryIcon03Active,
         primaryText01,
         primaryText02,
         primaryText02Selected,
         primaryField01,
         primaryField01Active,
         primaryField02,
         primaryField02Active,
         primaryField03,
         primaryField03Active,
         primaryInteractive01,
         primaryInteractive01Hover,
         primaryInteractive01Active,
         primaryInteractive01Disabled,
         primaryInteractive02,
         primaryInteractive02Hover,
         primaryInteractive02Active,
         primaryInteractive03,
         secondaryUi01,
         secondaryUi02,
         secondaryIcon01,
         secondaryIcon02,
         secondaryText01,
         secondaryText02,
         secondaryField01,
         secondaryField01Active,
         secondaryInteractive01,
         secondaryInteractive01Hover,
         secondaryInteractive01Active,
         podcastUi01,
         podcastUi02,
         podcastUi03,
         podcastUi04,
         podcastUi05,
         podcastUi06,
         podcastIcon01,
         podcastIcon02,
         podcastIcon03,
         podcastText01,
         podcastText02,
         podcastInteractive01,
         podcastInteractive01Active,
         podcastInteractive02,
         podcastInteractive03,
         podcastInteractive03Active,
         podcastInteractive04,
         podcastInteractive05,
         podcastOndark,
         podcastOnlight,
         filterUi01,
         filterUi02,
         filterUi03,
         filterUi04,
         filterIcon01,
         filterIcon02,
         filterText01,
         filterText02,
         filterInteractive01,
         filterInteractive01Active,
         filterInteractive02,
         filterInteractive03,
         filterInteractive03Active,
         filterInteractive04,
         filterInteractive05,
         filterInteractive06,
         support01,
         support02,
         support03,
         support04,
         support05,
         support06,
         support07,
         support08,
         support09,
         support10,
         playerBackground01,
         playerBackground02,
         playerHighlight01,
         playerHighlight02,
         playerHighlight03,
         playerHighlight04,
         playerHighlight05,
         playerHighlight06,
         playerHighlight07,
         playerContrast01,
         playerContrast02,
         playerContrast03,
         playerContrast04,
         playerContrast05,
         playerContrast06,
         contrast01,
         contrast02,
         contrast03,
         contrast04,
         filter01,
         filter02,
         filter03,
         filter04,
         filter05,
         filter06,
         filter07,
         filter08,
         filter09,
         filter10,
         filter11,
         filter12,
         veil,
         gradient01A,
         gradient01E,
         gradient02A,
         gradient02E,
         gradient03A,
         gradient03E,
         gradient04A,
         gradient04E,
         gradient05A,
         gradient05E,
         imageFilter01,
         imageFilter02,
         imageFilter03,
         imageFilter04,
         category01,
         category02,
         category03,
         category04,
         category05,
         category06,
         category07,
         category08,
         category09,
         category10,
         category11,
         category12,
         category13,
         category14,
         category15,
         category16,
         category17,
         category18,
         category19
}

nonisolated extension ThemeStyle {
    /// ThemeColorTable token for styles resolvable without extra parameters.
    static let simpleTokens: [ThemeStyle: String] = [
        .primaryUi01: "primaryUi01",
        .primaryUi01Active: "primaryUi01Active",
        .primaryUi02: "primaryUi02",
        .primaryUi02Selected: "primaryUi02Selected",
        .primaryUi02Active: "primaryUi02Active",
        .primaryUi03: "primaryUi03",
        .primaryUi04: "primaryUi04",
        .primaryUi05: "primaryUi05",
        .primaryUi05Selected: "primaryUi05Selected",
        .primaryUi06: "primaryUi06",
        .primaryIcon01: "primaryIcon01",
        .primaryIcon01Active: "primaryIcon01Active",
        .primaryIcon02: "primaryIcon02",
        .primaryIcon02Selected: "primaryIcon02Selected",
        .primaryIcon02Active: "primaryIcon02Active",
        .primaryIcon03: "primaryIcon03",
        .primaryIcon03Active: "primaryIcon03Active",
        .primaryText01: "primaryText01",
        .primaryText02: "primaryText02",
        .primaryText02Selected: "primaryText02Selected",
        .primaryField01: "primaryField01",
        .primaryField01Active: "primaryField01Active",
        .primaryField02: "primaryField02",
        .primaryField02Active: "primaryField02Active",
        .primaryField03: "primaryField03",
        .primaryField03Active: "primaryField03Active",
        .primaryInteractive01: "primaryInteractive01",
        .primaryInteractive01Hover: "primaryInteractive01Hover",
        .primaryInteractive01Active: "primaryInteractive01Active",
        .primaryInteractive01Disabled: "primaryInteractive01Disabled",
        .primaryInteractive02: "primaryInteractive02",
        .primaryInteractive02Hover: "primaryInteractive02Hover",
        .primaryInteractive02Active: "primaryInteractive02Active",
        .primaryInteractive03: "primaryInteractive03",
        .secondaryUi01: "secondaryUi01",
        .secondaryUi02: "secondaryUi02",
        .secondaryIcon01: "secondaryIcon01",
        .secondaryIcon02: "secondaryIcon02",
        .secondaryText01: "secondaryText01",
        .secondaryText02: "secondaryText02",
        .secondaryField01: "secondaryField01",
        .secondaryField01Active: "secondaryField01Active",
        .secondaryInteractive01: "secondaryInteractive01",
        .secondaryInteractive01Hover: "secondaryInteractive01Hover",
        .secondaryInteractive01Active: "secondaryInteractive01Active",
        .support01: "support01",
        .support02: "support02",
        .support03: "support03",
        .support04: "support04",
        .support05: "support05",
        .support06: "support06",
        .support07: "support07",
        .support08: "support08",
        .support09: "support09",
        .support10: "support10",
        .playerContrast01: "playerContrast01",
        .playerContrast02: "playerContrast02",
        .playerContrast03: "playerContrast03",
        .playerContrast04: "playerContrast04",
        .playerContrast05: "playerContrast05",
        .playerContrast06: "playerContrast06",
        .contrast01: "contrast01",
        .contrast02: "contrast02",
        .contrast03: "contrast03",
        .contrast04: "contrast04",
        .filter01: "filter01",
        .filter02: "filter02",
        .filter03: "filter03",
        .filter04: "filter04",
        .filter05: "filter05",
        .filter06: "filter06",
        .filter07: "filter07",
        .filter08: "filter08",
        .filter09: "filter09",
        .filter10: "filter10",
        .filter11: "filter11",
        .filter12: "filter12",
        .veil: "veil",
        .gradient01A: "gradient01A",
        .gradient01E: "gradient01E",
        .gradient02A: "gradient02A",
        .gradient02E: "gradient02E",
        .gradient03A: "gradient03A",
        .gradient03E: "gradient03E",
        .gradient04A: "gradient04A",
        .gradient04E: "gradient04E",
        .gradient05A: "gradient05A",
        .gradient05E: "gradient05E",
        .imageFilter01: "imageFilter01",
        .imageFilter02: "imageFilter02",
        .imageFilter03: "imageFilter03",
        .imageFilter04: "imageFilter04",
        .category01: "category01",
        .category02: "category02",
        .category03: "category03",
        .category04: "category04",
        .category05: "category05",
        .category06: "category06",
        .category07: "category07",
        .category08: "category08",
        .category09: "category09",
        .category10: "category10",
        .category11: "category11",
        .category12: "category12",
        .category13: "category13",
        .category14: "category14",
        .category15: "category15",
        .category16: "category16",
        .category17: "category17",
        .category18: "category18",
        .category19: "category19"
    ]

    /// The ThemeColorTable token backing this style, or nil for the
    /// parameterized families that need a podcast/filter colour at runtime.
    var simpleToken: String? {
        Self.simpleTokens[self]
    }
}
