# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# This pipeline is meant to be triggered by release automation.

agents:
  queue: macos-large

steps:
  - label: "New Beta Release"
    command: |
      echo '--- Configure Git identity'
      .buildkite/commands/use-bot-for-git.sh

      .buildkite/commands/checkout-release-branch.sh "${RELEASE_VERSION}"
      .buildkite/commands/shared_setup.sh --skip-swiftpm

      echo '--- Access Secrets'
      bundle exec fastlane run configure_apply

      echo '--- New Beta Release'
      bundle exec fastlane new_beta_release skip_confirm:true
    retry:
      manual:
        reason: If release jobs fail, re-trigger the release task rather than retrying this individual job.
        allowed: false
