name: ☢️ Trigger Danger On Buildkite

on:
  pull_request:
    types: [labeled, unlabeled, milestoned, demilestoned, ready_for_review, edited]

jobs:
  dangermattic:
    if: ${{ github.event.pull_request.draft == false && vars.ENABLE_BUILDKITE_DANGER_RETRY == 'true' }}
    uses: Automattic/dangermattic/.github/workflows/reusable-retry-buildkite-step-on-events.yml@595269bb89f8efffd47556e4182f0085053d2313
    with:
      org-slug: hbmartin
      pipeline-slug: pocket-casts-ios
      retry-step-key: danger
      build-commit-sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      buildkite-api-token: ${{ secrets.TRIGGER_BK_BUILD_TOKEN }}
