name: Swift Package Version Updates

on:
  pull_request:
    paths:
      - "Modules/Package.swift"
      - "Modules/Package.resolved"
      - "BuildTools/Package.swift"
      - "BuildTools/Package.resolved"
      - ".swiftlint.yml"
      - ".github/workflows/spm-version-updates.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spm-version-updates:
    name: Check SPM Dependencies
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false

      - name: Check Swift package updates
        # c3cbe21c807e8a99fd61dba23c0d5476725a5a18 is v1.2.0.
        uses: hbmartin/github-action-spm_version_updates@c3cbe21c807e8a99fd61dba23c0d5476725a5a18
        with:
          package-manifest-paths: |
            Modules/Package.swift
            BuildTools/Package.swift
          report-above-maximum: true
          allow-hosts: github.com
